import test from 'node:test';import assert from 'node:assert/strict';import {handle,validateItems} from './worker.mjs';
const catalog={example:{available:true,stripePriceId:'price_example',unitAmount:2500,currency:'usd'}};
const env={STRIPE_SECRET_KEY:'sk_test_fixture',ALLOWED_ORIGINS:'https://parametric.space',SITE_URL:'https://parametric.space',PRICE_CATALOG_JSON:JSON.stringify(catalog),CHECKOUT_RATE_LIMITER:{limit:async()=>({success:true})}};
const body={items:[{id:'example',quantity:2}],requestId:'12345678-1234-1234-1234-123456789012'};
function req(data=body,origin='https://parametric.space'){return new Request('https://worker.test/checkout',{method:'POST',headers:{Origin:origin,'CF-Connecting-IP':'192.0.2.1','Content-Type':'application/json'},body:JSON.stringify(data)});}
const noCall=()=>{throw Error('Unexpected network request');};
test('rejects tampered ids, duplicate lines, and invalid quantities',()=>{for(const items of [[{id:'evil',quantity:1}],[{id:'example',quantity:-1}],[{id:'example',quantity:1.2}],[{id:'example',quantity:11}],[{id:'example',quantity:1},{id:'example',quantity:1}]])assert.throws(()=>validateItems(items,catalog));});
test('builds checkout from trusted Stripe prices, ignoring browser prices',async()=>{const calls=[];const response=await handle(req({...body,items:[{id:'example',quantity:2,unitAmount:1}],success_url:'https://evil.test'}),env,async(url,options)=>{calls.push({url,options});return Response.json(url.includes('/prices/')?{active:true,type:'one_time',unit_amount:2500,currency:'usd',livemode:false}:{url:'https://checkout.stripe.com/c/pay/test'});});assert.equal(response.status,200);const params=calls[1].options.body;assert.equal(params.get('line_items[0][price]'),'price_example');assert.equal(params.get('line_items[0][quantity]'),'2');assert.match(params.get('success_url'),/^https:\/\/parametric.space\/checkout-result/);assert.ok(params.get('success_url').includes('{CHECKOUT_SESSION_ID}'));});
test('blocks foreign origins and live keys by default',async()=>{assert.equal((await handle(req(body,'https://evil.test'),env,noCall)).status,403);assert.equal((await handle(req(),{...env,STRIPE_SECRET_KEY:'sk_live_fixture'},noCall)).status,503);});
test('missing configuration and empty catalogue cannot charge',async()=>{assert.equal((await handle(req(),{...env,STRIPE_SECRET_KEY:''},noCall)).status,503);assert.equal((await handle(req(),{...env,PRICE_CATALOG_JSON:'{}'},noCall)).status,503);});
test('stale Stripe prices cannot be charged silently',async()=>{assert.equal((await handle(req(),env,async()=>Response.json({active:true,type:'one_time',unit_amount:3000,currency:'usd',livemode:false}))).status,409);});
test('provider failures do not produce checkout URL',async()=>{const r=await handle(req(),env,async()=>new Response('failed',{status:500}));assert.equal(r.status,502);assert.equal((await r.json()).url,undefined);});
test('status is read from Stripe and exposes no customer data',async()=>{const r=await handle(new Request('https://worker.test/session?session_id=cs_test_example',{headers:{Origin:'https://parametric.space','CF-Connecting-IP':'192.0.2.1'}}),env,async()=>Response.json({metadata:{site:'parametric-space'},payment_status:'unpaid',livemode:false,customer_email:'private@example.com'}));assert.deepEqual(await r.json(),{paymentStatus:'unpaid',testMode:true});});
