import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
export async function mountModelViewer(host,modelUrl){
 const canvas=document.createElement('canvas');canvas.setAttribute('aria-label','Rotating arowana concept model. Use drag, scroll, or the view controls below.');canvas.tabIndex=0;
 const stage=document.createElement('div');stage.className='model-stage';stage.append(canvas);host.append(stage);
 const status=document.createElement('p');status.className='viewer-status';status.setAttribute('role','status');status.textContent='Loading 3D model…';host.append(status);
 let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});}catch{status.textContent='3D is unavailable in this browser. The reference photo is shown below.';stage.remove();return;}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(-.1,1.8,12.5);
 scene.add(new THREE.HemisphereLight(0xffffff,0xa1a5bf,2.5));for(const [x,y,z,power] of [[-5,7,6,3],[5,2,-5,2],[0,-3,5,1]]){const light=new THREE.DirectionalLight(0xffffff,power);light.position.set(x,y,z);scene.add(light);}
 const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=7;controls.maxDistance=26;controls.target.set(.1,0,0);controls.autoRotate=!matchMedia('(prefers-reduced-motion: reduce)').matches;controls.autoRotateSpeed=1.3;
 const toolbar=document.createElement('div');toolbar.className='model-controls';host.append(toolbar);
 function button(text,fn){const b=document.createElement('button');b.type='button';b.textContent=text;b.addEventListener('click',fn);toolbar.append(b);return b;}
 const pause=button(controls.autoRotate?'Pause rotation':'Start rotation',()=>{controls.autoRotate=!controls.autoRotate;pause.textContent=controls.autoRotate?'Pause rotation':'Start rotation';pause.setAttribute('aria-pressed',String(controls.autoRotate));});pause.setAttribute('aria-pressed',String(controls.autoRotate));
 button('Front',()=>{camera.position.set(.1,.3,13);controls.target.set(.1,0,0);controls.update();});button('Back',()=>{camera.position.set(.1,.3,-13);controls.update();});button('Reset view',()=>{camera.position.set(-.1,1.8,12.5);controls.target.set(.1,0,0);controls.update();});
 canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key))return;e.preventDefault();const offset=camera.position.clone().sub(controls.target);if(e.key==='ArrowLeft'||e.key==='ArrowRight')offset.applyAxisAngle(new THREE.Vector3(0,1,0),e.key==='ArrowLeft'?.16:-.16);else if(e.key==='ArrowUp'||e.key==='ArrowDown')offset.y+=e.key==='ArrowUp'?.3:-.3;else offset.multiplyScalar(e.key==='+'?.9:1.1);offset.clampLength(7,26);camera.position.copy(controls.target).add(offset);controls.update();});
 const resize=()=>{const width=stage.clientWidth,height=stage.clientHeight;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();const fit=4.6/(Math.tan(THREE.MathUtils.degToRad(18))*camera.aspect);const offset=camera.position.clone().sub(controls.target);if(offset.length()<fit)camera.position.copy(controls.target).add(offset.setLength(Math.min(fit,26)));controls.update();};const observer=new ResizeObserver(resize);observer.observe(stage);resize();
 try{const gltf=await new GLTFLoader().loadAsync(modelUrl);scene.add(gltf.scene);status.textContent='Drag to rotate · Scroll or pinch to zoom';}catch{status.textContent='The model could not load. View the reference photo below.';observer.disconnect();renderer.dispose();stage.remove();toolbar.remove();return;}
 let visible=true;const intersection=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;});intersection.observe(stage);const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(!visible||document.hidden)return;controls.update(dt);renderer.render(scene,camera);});
 window.addEventListener('pagehide',()=>{renderer.setAnimationLoop(null);observer.disconnect();intersection.disconnect();controls.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});renderer.dispose();},{once:true});
}
